from pathlib import Path
from bs4 import BeautifulSoup
import logging

# Настройка логирования
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

try:
    from tech_facts_db import TECH_FACTS_DB
except ImportError:
    TECH_FACTS_DB = {}

try:
    from auto_tech_facts_db import AUTO_TECH_FACTS_DB
except ImportError:
    AUTO_TECH_FACTS_DB = {}

try:
    from tech_facts_db_extra import TECH_FACTS_DB_EXTRA
except ImportError:
    TECH_FACTS_DB_EXTRA = {}

ROOT_DIR = Path(".")

APPLIANCE_TYPES = {
    "naprawa-pralek": "pralki",
    "naprawa-lodowek": "lodówki",
    "naprawa-zmywarek": "zmywarki",
    "naprawa-piekarnikow": "piekarniki",
    "naprawa-suszarek": "suszarki",
    "naprawa-pralko-suszarek": "pralko-suszarki",
}

PROTECTED_CLASSES = {
    'unique-ai-content',
    'ai-generated',
    'seo-content',
    'article-content',
    'blog-post',
    'service-description',
}

DEFAULT_FALLBACK_ERRORS = [
    {"code": "E01 / F01", "cause": "Błąd blokady drzwi lub czujnika zamknięcia", "part": "blokada drzwi / moduł"},
    {"code": "E02 / F02", "cause": "Problem z dopływem wody lub zaworem ssącym", "part": "elektrozawór / filtr"},
    {"code": "E03 / F03", "cause": "Problem z odpływem wody lub zablokowana pompa", "part": "pompa odpływowa / filtr"},
    {"code": "E04 / F04", "cause": "Weryfikacja obwodu grzania i czujnika NTC", "part": "grzałka / czujnik NTC"},
    {"code": "E05 / F05", "cause": "Usterka silnika lub zużycie szczotek węglowych", "part": "szczotki silnika / prądniczka"}
]

def get_all_brands():
    """Автоматически собирает список известных брендов."""
    brands = set()
    for db in [TECH_FACTS_DB, AUTO_TECH_FACTS_DB, TECH_FACTS_DB_EXTRA]:
        if isinstance(db, dict):
            brands.update(db.keys())
    return list(brands)

ALL_BRANDS = get_all_brands()

def extract_brand_name(soup: BeautifulSoup, file_path: Path) -> str:
    """Точно определяет название бренда из пути или заголовков."""
    path_str = str(file_path).lower()
    for b in ALL_BRANDS:
        if b in path_str:
            return b

    for tag in soup.find_all(['h1', 'h2']):
        text = tag.get_text().lower()
        for b in ALL_BRANDS:
            if b in text:
                return b

    return file_path.stem.lower()

def is_protected_element(element) -> bool:
    """Проверяет, находится ли элемент в защищённой зоне (AI-контент/статьи)."""
    parent = element.parent
    while parent:
        if parent.get('class'):
            parent_classes = set(parent.get('class', []))
            if parent_classes & PROTECTED_CLASSES:
                return True
        
        if parent.name == 'section' and parent.get('class'):
            if 'unique-ai-content' in parent.get('class', []):
                return True
        
        parent = parent.parent
    
    if element.get('id'):
        element_id = element.get('id', '').lower()
        protected_ids = ['ai-content', 'seo-content', 'article']
        if any(pid in element_id for pid in protected_ids):
            return True
    
    return False

def should_clean_list(ul_tag) -> bool:
    """Проверяет, является ли список мусорным шаблоном кодов ошибок."""
    if is_protected_element(ul_tag):
        return False
    
    ul_text = ul_tag.get_text().lower()
    
    # 1. Защита от удаления AI-контента по ключевым мета-маркерам
    ai_markers = ['generated by ai', 'ai-generated', 'sztuczna inteligencja']
    if any(marker in ul_text for marker in ai_markers):
        return False

    # 2. ПРЯМОЙ ПОИСК МУСОРА: очищаем ТОЛЬКО если найдены явные маркеры фейковых/шаблонных ошибок
    garbage_markers = [
        'wymaga diagnozy technicznej',
        'awaria układu: ułożenie',
        'błąd systemowy: konieczność',
        'usterka elektroniczna: diagnostyka',
        'problem z modułem sterującym',
        'uszkodzenie czujnika temperatury',
        'awaria pompy obiegowej',
        'zużycie elementów grzejnych'
    ]
    
    for marker in garbage_markers:
        if marker in ul_text:
            return True

    # 3. Проверка контекста: если предшествующий заголовок говорит про коды ошибок, а внутри шаблоны
    prev = ul_tag.find_previous_sibling()
    if prev and any(kw in prev.get_text().lower() for kw in ["kod", "błąd", "błędy"]):
        if "kod" in ul_text and ("usterka" in ul_text or "wymaga" in ul_text):
            return True
    
    return False

def get_brand_data(brand_name: str, appliance_type: str = None):
    """Глубокий поиск данных бренда во всех подключенных словарях."""
    for db in [TECH_FACTS_DB, AUTO_TECH_FACTS_DB, TECH_FACTS_DB_EXTRA]:
        if not isinstance(db, dict):
            continue
            
        if brand_name in db:
            data = db[brand_name]
            
            if isinstance(data, list):
                return data
            
            if isinstance(data, dict):
                if appliance_type and appliance_type in data:
                    sub_data = data[appliance_type]
                    if isinstance(sub_data, dict) and "common_errors" in sub_data:
                        return sub_data["common_errors"]
                
                for key, value in data.items():
                    if isinstance(value, dict) and "common_errors" in value:
                        return value["common_errors"]
    
    return None

def fix_html_file(file_path: Path):
    """Безопасная очистка только мусорных списков."""
    appliance_type = None
    for folder in APPLIANCE_TYPES.keys():
        if folder in str(file_path):
            appliance_type = folder
            break
            
    try:
        content = file_path.read_text(encoding="utf-8", errors="ignore")
        soup = BeautifulSoup(content, "html.parser")
        modified = False
        
        current_brand = extract_brand_name(soup, file_path)
        
        for ul in soup.find_all(['ul', 'ol']):
            if not should_clean_list(ul):
                continue
            
            logging.info(f"  🧹 Замена списка ошибок ({current_brand}) в {file_path.name}")
            
            errors_list = get_brand_data(current_brand, appliance_type)
            if not errors_list:
                logging.warning(f"  ⚠️ Нет данных в БД для '{current_brand}', задействован fallback")
                errors_list = DEFAULT_FALLBACK_ERRORS
            
            new_lis = []
            for err in errors_list[:8]:
                code = err.get('code', 'Błąd')
                cause = err.get('cause', 'Wymaga weryfikacji')
                part = err.get('part', 'diagnostyka')
                new_lis.append(
                    f"<li><strong>Kod {code}</strong> – {cause} "
                    f"<span style='color: #9da5b1; font-size: 0.9rem;'>(kontrola: {part})</span>.</li>"
                )
            
            ul_classes = ul.get('class', [])
            ul_class_str = f" class=\"{' '.join(ul_classes)}\"" if ul_classes else ""
            
            new_ul_html = f"<ul{ul_class_str}>\n" + "\n".join(new_lis) + "\n</ul>"
            new_ul = BeautifulSoup(new_ul_html, 'html.parser')
            
            ul.clear()
            for child in new_ul.children:
                ul.append(child)
            
            modified = True
        
        if modified:
            file_path.write_text(str(soup), encoding="utf-8")
            return True
        
        return False
        
    except Exception as e:
        logging.error(f"  ❌ Ошибка при обработке {file_path.name}: {e}")
        return False

def main():
    print("=" * 60)
    print("БЕЗОПАСНАЯ ОЧИСТКА КОДОВ ОШИБОК v3.0")
    print("=" * 60)
    
    processed = 0
    cleaned = 0
    skipped = 0
    
    for path in ROOT_DIR.rglob("*.html"):
        if path.stem == "index" or any(p in path.parts for p in [".git", "node_modules", ".vscode"]):
            continue
        
        processed += 1
        if fix_html_file(path):
            cleaned += 1
        else:
            skipped += 1
    
    print("\n" + "=" * 60)
    print(f"📊 ИТОГОВАЯ СТАТИСТИКА:")
    print(f"   Обработано HTML-файлов: {processed}")
    print(f"   Успешно очищено:       {cleaned}")
    print(f"   Пропущено без изменений: {skipped}")
    print("=" * 60)

if __name__ == "__main__":
    main()